version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    user : mysql
    container_name:
     mysql_server
    environment:
      MYSQL_DATABASE: gp-db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
  api:
    container_name:
      api_server
    depends_on:
        - db
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://username:password@db:3306/gp-db
    networks:
      - mysql_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mysql_network:


volumes:
  mysql_data: