version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    user : mysql
    secrets:
    - db_password
    ports:
    - "6666:3306"
    container_name:
     mysql_server
    environment:
      MYSQL_DATABASE: gp-db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
  api:
    container_name:
      api_server
    depends_on:
        - db
    build: .
    secrets:
      - db_password
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://username:password@db:3306/gp-db
    networks:
      - mysql_network

networks:
  mysql_network:

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  mysql_data: