version: "3.9"
services:
  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres
    restart: always
    user : postgres
    secrets:
      - db_password
    ports:
      - "6666:5432"
    container_name: postgres_server
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gp-db
    networks:
      - postgres_network
  api:
    container_name: api_server
    depends_on:
      - db
    build: .
    secrets:
      - db_password
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://username:password@db:6666/gp-db
    networks:
      - postgres_network

networks:
  postgres_network:

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
    postgres_data:

